site_name: "neopy"
site_description: "Neo4j for Python. Manipulate graph data in Python with Neo4j as data storage."
site_url: "https://pawamoy.github.io/neopy"
repo_url: "https://github.com/pawamoy/neopy"
repo_name: "pawamoy/neopy"

nav:
  - Overview: index.md
  - API Reference:
    - cli.py: reference/cli.md
    - cypher.py: reference/cypher.md
    - db.py: reference/db.md
    - enums.py: reference/enums.md
    - examples.py: reference/examples.md
    - exceptions.py: reference/exceptions.md
    - functions.py: reference/functions.md
    - graph.py: reference/graph.md
    - utils.py: reference/utils.md
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Changelog: changelog.md
  - Credits: credits.md

theme:
  name: material

extra_css:
  - css/mkdocstrings.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"

plugins:
  - search
  - mkdocstrings:
      watch:
        - src/neopy
